version: '3.4'

services:

    reverse-proxy:
        build:
            context: ./BoardGames.Proxy
        ports:
            - "5110:80"
            - "5111:5001"
        networks:
            - overlay
        depends_on:
            - frontend

    frontend:
        build:
            context: ./BoardGames.Client
        networks:
            - overlay
        depends_on:
            - backend

    backend:
        build:
            context: ./BoardGames.Api
        networks:
            - overlay
        depends_on:
            - postgres-db     

    postgres-db:
        image: postgres
        networks:
            - overlay
        environment:
            POSTGRES_USER: "board_games_user"
            POSTGRES_PASSWORD: "board_games_pass"
            POSTGRES_DB: "board_games"

networks:
    overlay:
